# -*- coding: utf-8 -*-
"""POINT CLOUD 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCwm4TLya1G4DGEGIO6Bw0oqtJWb_qSS
"""

import time
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from ripser import ripser
from persim import plot_diagrams

TICKER = "CIFR"
START  = "2022-01-01"
END    = "2026-01-01"

TRADING_DAYS_PER_YEAR = 252
WINDOW_DAYS = 252
EMBED_W = 30
VIS_WINDOW_INDEX = 0

px = yf.download(TICKER, start=START, end=END, auto_adjust=True, progress=False)["Close"].dropna()
if len(px) < 3:
    raise ValueError("Not enough price data")

x = np.log(px).to_numpy().reshape(-1)
if len(x) < EMBED_W + 2:
    raise ValueError("Not enough log-price points to embed")

def embed(arr, W):
    arr = np.asarray(arr).reshape(-1)
    n = len(arr)
    if n < W:
        raise ValueError("too short for embedding")
    return np.vstack([arr[i:i+W] for i in range(n - W + 1)])

def rolling_slices(n, window_len, step_len):
    out = []
    for s in range(0, n - window_len + 1, step_len):
        out.append((s, s + window_len))
    return out

slices = rolling_slices(len(x), WINDOW_DAYS, TRADING_DAYS_PER_YEAR)
if not slices:
    raise ValueError("no windows")

s, e = slices[int(np.clip(VIS_WINDOW_INDEX, 0, len(slices)-1))]
x_win = x[s:e]

X = embed(x_win, EMBED_W)
X = X - X.mean(axis=1, keepdims=True)

k = min(3, X.shape[0], X.shape[1])
Xp = PCA(n_components=k).fit_transform(X)

if k == 1:
    plt.figure()
    plt.plot(Xp[:, 0], ".", markersize=3)
    plt.title(f"{TICKER} point cloud (PCA 1D)")
    plt.show()
elif k == 2:
    plt.figure()
    plt.scatter(Xp[:, 0], Xp[:, 1], s=6)
    plt.title(f"{TICKER} point cloud (PCA 2D)")
    plt.show()
else:
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(Xp[:, 0], Xp[:, 1], Xp[:, 2], s=6)
    ax.set_title(f"{TICKER} point cloud (PCA 3D)")
    plt.show()

print("x shape:", x.shape)
print("X shape:", X.shape)
print("running ripser...")

t0 = time.perf_counter()
out = ripser(X, maxdim=1)
t1 = time.perf_counter()
print("ripser seconds:", round(t1 - t0, 6))

dgms = out["dgms"]
H0, H1 = dgms[0], dgms[1]

print("H0 total:", len(H0), "| H0 finite deaths:", int(np.isfinite(H0[:, 1]).sum()))
print("H1 total:", len(H1), "| H1 finite deaths:", int(np.isfinite(H1[:, 1]).sum()))

fig, ax = plt.subplots()
plot_diagrams(dgms, ax=ax, show=False)
ax.set_title(f"{TICKER} VR persistence | W={EMBED_W}")
plt.show()

pip install yfinance numpy pandas matplotlib scikit-learn ripser persim