# -*- coding: utf-8 -*-
"""Vietoris Rips filtration 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPKp3WRcSGz7-E4ewm8PEKnFFBH5saw1
"""

import time
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from ripser import ripser

# ASSET PICK AND DATE WINDOWS
TICKER = "spy"
START  = "2000-01-01"
END    = "2026-01-01"

WINDOW_DAYS = 252      # 1 year window 252, 6 month 126
STEP_DAYS   = 21  # 21 - monthly,  5 for weekly
EMBED_W     = 60      # try 30-80
USE_PCA3_FOR_RIPSER = True  # keeps it fast + simple

EVENT_DATE = np.datetime64("2008-09-15")

px = yf.download(TICKER, start=START, end=END, auto_adjust=True, progress=False)["Close"].dropna()
if len(px) < 10:
    raise ValueError("Not enough price data")

# RETURNS ONLY
x = np.diff(np.log(px.to_numpy().reshape(-1)))
ret_dates = px.index[1:]   # dates for returns
if len(x) < WINDOW_DAYS + 5:
    raise ValueError("Not enough return data for chosen WINDOW_DAYS")

def embed(arr, W):
    arr = np.asarray(arr).reshape(-1)
    n = len(arr)
    if n < W:
        raise ValueError("too short for embedding")
    return np.vstack([arr[i:i+W] for i in range(n - W + 1)])

def rolling_slices(n, window_len, step_len):
    out = []
    for s in range(0, n - window_len + 1, step_len):
        out.append((s, s + window_len))
    return out

slices = rolling_slices(len(x), WINDOW_DAYS, STEP_DAYS)
if not slices:
    raise ValueError("no windows (check WINDOW_DAYS / STEP_DAYS)")

scores = []
end_dates = []

t0 = time.perf_counter()
for (s, e) in slices:
    x_win = x[s:e]

    X = embed(x_win, EMBED_W)
    X = X - X.mean(axis=1, keepdims=True)

    Y = X
    if USE_PCA3_FOR_RIPSER and min(X.shape) >= 3:
        Y = PCA(n_components=3).fit_transform(X)

    out = ripser(Y, maxdim=1)
    H1 = out["dgms"][1]

    # Simple H1 signal options
    # persistence lengths
    finite = np.isfinite(H1[:, 1])
    if finite.any():
        pers = H1[finite, 1] - H1[finite, 0]
        pers.sort()
        # score = pers[-1]                 # max persistence
        score = pers[-3:].sum()            # sum of top 3 (more stable)
    else:
        score = 0.0

    scores.append(float(score))
    end_dates.append(ret_dates[e - 1])

t1 = time.perf_counter()
print("windows:", len(slices), "| seconds:", round(t1 - t0, 3))

scores = np.array(scores)
end_dates = np.array(end_dates, dtype="datetime64[D]")

# Plot the signal
plt.figure()
plt.plot(end_dates, scores, ".-")
plt.axvline(EVENT_DATE, linestyle="--")
plt.title(f"{TICKER} H1 signal (top3 persistence sum)\nreturns | WINDOW={WINDOW_DAYS} STEP={STEP_DAYS} W={EMBED_W}")
plt.xlabel("window end date")
plt.ylabel("H1 score")
plt.show()

# "Identify" = show biggest spikes
k = 10
top_idx = np.argsort(scores)[-k:][::-1]
print(f"Top {k} windows by score:")
for i in top_idx:
    print(str(end_dates[i]), "score=", round(scores[i], 6))

# Simple threshold flag (top 5% as "crisis")
thr = np.quantile(scores, 0.95)
flag_dates = end_dates[scores >= thr]
print("Flagged (top 5%) window end dates:", [str(d) for d in flag_dates[:20]], "...")

!nvidia-smi

pip install yfinance numpy pandas matplotlib scikit-learn ripser persim